language: php
notifications:
  email: false
php:
    - 7.2
    - 7.3
    - 7.4
script:
    - composer test
before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source
